// tool-test/webpack5/src/solid/app.jsx
// App.JSX
import { render } from 'solid-js/web';
import { StkTable } from './StkTable.jsx';
import {stkTableColumns,stkTableData} from '../stk-table/props.js'


function App() {
  return <div>
    <h1>Solid App</h1>
    <StkTable style="height:300px" columns={stkTableColumns} dataSource={stkTableData}></StkTable>
  </div>;
}
// 组件声明也可以直接用箭头函数
/*
const App = ()=> (<div>Solid My App</div>);
*/

render(() => <App />, document.querySelector('#solid-app'));

// tool-test/webpack5/src/vue/App.vue
<script setup>
import { ref } from 'vue';
import StkTable from './StkTable.vue';
import {stkTableColumns,stkTableData} from '../stk-table/props.js'

const count = ref(0);

function countPlus() {
  count.value++;
}
</script>

<template>
  <div>
    <h2>Vue3 App</h2>
    <button @click="countPlus">count++ {{ count }}</button>
    <StkTable style="height:300px" :columns="stkTableColumns" :data-source="stkTableData"></StkTable>
  </div>
</template>
