// projects/yb-ocr/src/App.svelte
<script lang="ts">
  import FileInput from './lib/FileInput.svelte';
</script>

<main>
  <div class="input-file-content">
    <FileInput />
  </div>
  <pre class="text-content">TODO:</pre>
</main>

<style lang="less">
  main {
    display: flex;
    height: 100%;
    display: grid;
    grid-template-rows: 100%;
    grid-template-columns: 300px 1fr;
    gap: var(--gap);
    padding: var(--gap);

    .input-file-content {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: flex-start;
    }
    .text-content {
      flex: 1;
      border: 2px solid #aaa;
      border-radius: var(--border-radius);
      margin: 0;
    }
  }
</style>

// vue-component/App.vue
<template lang="pug">
VirtualTree
VirtualTreeSelectTest
EasyTableTest
 
</template>

<script>
import VirtualTree from './test/VirtualTree.vue';
import EasyTableTest from './test/EasyTableTest.vue';
import VirtualTreeSelectTest from './test/VirtualTreeSelect.vue';
export default {
  components: {
    VirtualTree,
    EasyTableTest,
    VirtualTreeSelectTest,
  },
};
</script>

<style>
body {
  height: 100vh;
  /* margin: 0; */
  box-sizing: border-box;
  /* padding: 10px; */
  display: flex;
  /* flex-direction: column; */
  /* align-items: center; */
  /* justify-content: center; */
}
</style>
